# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = "cinch-tinychat"
  s.version = "1.0.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Richard Banks"]
  s.date = "2014-09-02"
  s.description = "The TinyChat plugin will query the room you ask it to and return with information on it."
  s.email = "namaste@rawrnet.net"
  s.extra_rdoc_files = [
    "LICENSE",
    "README.rdoc"
  ]
  s.files = [
    "LICENSE",
    "README.rdoc",
    "lib/cinch/plugins/tiny_chat.rb"
  ]
  s.homepage = "http://github.com/namasteh/cinch-tinychat"
  s.require_paths = ["lib"]
  s.rubygems_version = "1.8.23"
  s.summary = "The TinyChat plugin will query the room you ask it to and return with information on it."

  if s.respond_to? :specification_version then
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<cinch>, [">= 0"])
      s.add_runtime_dependency(%q<nokogiri>, [">= 0"])
    else
      s.add_dependency(%q<cinch>, [">= 0"])
      s.add_dependency(%q<nokogiri>, [">= 0"])
    end
  else
    s.add_dependency(%q<cinch>, [">= 0"])
    s.add_dependency(%q<nokogiri>, [">= 0"])
  end
end

